### ISSUE TITLE
Issue starting up the project

### ISSUE THREAD

**Issue by marianmoldovan** [HectorRubi/pokedex-fullstack-tech-challenge#1]
Hello Hector,

I am havint his issue starting the challenge:
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'app'
Unsupported config option for volumes: 'data'
Unsupported config option for networks: 'pokedex'
make[1]: *** [simple-start] Error 1
make: *** [start] Error 2

Is this related to my docker compose version? I just updated and having the same issue.

These are my version:
docker-compose version 1.25.5, build unknown
Docker version 24.0.6, build ed223bc

**Comment by HectorRubi** [comment]
Hi, Marian

Thanks for sending me this error, It´s very usefull.
I´ve been updated the README, and adding a manual intallation section.
I hope this woks well for you and please send me any issue you have in the future.

Best regards,
Hector

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Marian C ***@***.***>
Enviado: lunes, 18 de septiembre de 2023 11:06
Para: ***@***.***>
CC: ***@***.***>
Asunto: [HectorRubi/pokedex-fullstack-tech-challenge] Issue starting up the project (Issue #1)


Hello Hector,

I am havint his issue starting the challenge:
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'app'
Unsupported config option for volumes: 'data'
Unsupported config option for networks: 'pokedex'
make[1]: *** [simple-start] Error 1
make: *** [start] Error 2

Is this related to my docker compose version? I just updated and having the same issue.

These are my version:
docker-compose version 1.25.5, build unknown
Docker version 24.0.6, build ed223bc

**Comment by HectorRubi** [comment]
Hi,
I forgoted just one command in the manual intallation, the npm install command
It's done now.

**Comment by marianmoldovan** [comment]
Amazing! Thanx @HectorRubi !
